name: review

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  core:
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v4

      - name: 🏗 Setup project
        uses: ./.github/actions/setup-project

      - name: 🚨 Lint core
        run: bun run lint -- --max-warnings 0

      - name: 📋 Typecheck core
        run: bun run typecheck

      - name: 👷 Build core
        run: bun run build

  webui:
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v4

      - name: 🏗 Setup project
        uses: ./.github/actions/setup-project
        with:
          with-webui: true

      - name: 📋 Typecheck webui
        run: bun run typecheck
        working-directory: webui

      - name: 👷 Build webui
        run: bun run build
        working-directory: webui
